// Code generated by SQLBoiler 4.1.2 (https://gitlab.etecs.ru/forks/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Flexies          string
	GrammarPositions string
}{
	Flexies:          "flexies",
	GrammarPositions: "grammar_positions",
}
