// Code generated by SQLBoiler 4.1.2 (https://gitlab.etecs.ru/forks/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"gitlab.etecs.ru/forks/sqlboiler/v4/drivers"
	"gitlab.etecs.ru/forks/sqlboiler/v4/queries"
	"gitlab.etecs.ru/forks/sqlboiler/v4/queries/qm"
)

var dialect = drivers.Dialect{
	LQ: 0x22,
	RQ: 0x22,

	UseIndexPlaceholders:    false,
	UseLastInsertID:         true,
	UseSchema:               false,
	UseDefaultKeyword:       true,
	UseAutoColumns:          false,
	UseTopClause:            false,
	UseOutputClause:         false,
	UseCaseWhenExistsClause: false,
}

// NewQuery initializes a new Query using the passed in QueryMods
func NewQuery(mods ...qm.QueryMod) *queries.Query {
	q := &queries.Query{}
	queries.SetDialect(q, &dialect)
	qm.Apply(q, mods...)

	return q
}
