output   = "models"
wipe = true
no-hooks = true

[sqlite3]
dbname = "../../test-db.db"
blacklist = ["schema_migrations"]

[aliases.tables.lemmas]
up_plural     = "Lemmas"
up_singular   = "Lemma"
down_plural   = "lemmas"
down_singular = "lemma"